const_value = 1

	const DEX_BULBASAUR     ; 1
	const DEX_IVYSAUR       ; 2
	const DEX_VENUSAUR      ; 3
	const DEX_CHARMANDER    ; 4
	const DEX_CHARMELEON    ; 5
	const DEX_CHARIZARD     ; 6
	const DEX_SQUIRTLE      ; 7
	const DEX_WARTORTLE     ; 8
	const DEX_BLASTOISE     ; 9
	const DEX_CATERPIE      ; 10
	const DEX_METAPOD       ; 11
	const DEX_BUTTERFREE    ; 12
	const DEX_WEEDLE        ; 13
	const DEX_KAKUNA        ; 14
	const DEX_BEEDRILL      ; 15
	const DEX_PIDGEY        ; 16
	const DEX_PIDGEOTTO     ; 17
	const DEX_PIDGEOT       ; 18
	const DEX_RATTATA       ; 19
	const DEX_RATICATE      ; 20
	const DEX_SPEAROW       ; 21
	const DEX_FEAROW        ; 22
	const DEX_EKANS         ; 23
	const DEX_ARBOK         ; 24
	const DEX_PIKACHU       ; 25
	const DEX_RAICHU        ; 26
	const DEX_GOROCHU       ; 27
	const DEX_SANDSHREW     ; 28
	const DEX_SANDSLASH     ; 29
	const DEX_NIDORAN_F     ; 30
	const DEX_NIDORINA      ; 31
	const DEX_NIDOQUEEN     ; 32
	const DEX_NIDORAN_M     ; 33
	const DEX_NIDORINO      ; 34
	const DEX_NIDOKING      ; 35
	const DEX_CLEFAIRY      ; 36
	const DEX_CLEFABLE      ; 37
	const DEX_VULPIX        ; 38
	const DEX_NINETALES     ; 39
	const DEX_JIGGLYPUFF    ; 40
	const DEX_WIGGLYTUFF    ; 41
	const DEX_ZUBAT         ; 42
	const DEX_GOLBAT        ; 43
	const DEX_CROBAT        ; 44
	const DEX_ODDISH        ; 45
	const DEX_GLOOM         ; 46
	const DEX_VILEPLUME     ; 47
	const DEX_PARAS         ; 48
	const DEX_PARASECT      ; 49
	const DEX_VENONAT       ; 50
	const DEX_VENOMOTH      ; 51
	const DEX_DIGLETT       ; 52
	const DEX_DUGTRIO       ; 53
	const DEX_MEOWTH        ; 54
	const DEX_PERSIAN       ; 55
	const DEX_PSYDUCK       ; 56
	const DEX_GOLDUCK       ; 57
	const DEX_MANKEY        ; 58
	const DEX_PRIMEAPE      ; 59
	const DEX_ANNIHILAPE    ; 60
	const DEX_GROWLITHE     ; 61
	const DEX_ARCANINE      ; 62
	const DEX_HOUNDOUR      ; 63
	const DEX_HOUNDOOM      ; 64
	const DEX_POLIWAG       ; 65
	const DEX_POLIWHIRL     ; 66
	const DEX_POLIWRATH     ; 67
	const DEX_ABRA          ; 68
	const DEX_KADABRA       ; 69
	const DEX_ALAKAZAM      ; 70
	const DEX_MACHOP        ; 71
	const DEX_MACHOKE       ; 72
	const DEX_MACHAMP       ; 73
	const DEX_BELLSPROUT    ; 74
	const DEX_WEEPINBELL    ; 75
	const DEX_VICTREEBEL    ; 76
	const DEX_TENTACOOL     ; 77
	const DEX_TENTACRUEL    ; 78
	const DEX_GEODUDE       ; 79
	const DEX_GRAVELER      ; 80
	const DEX_GOLEM         ; 81
	const DEX_SLUGMA        ; 82
	const DEX_MAGCARGO      ; 83
	const DEX_PONYTA        ; 84
	const DEX_RAPIDASH      ; 85
	const DEX_SLOWPOKE      ; 86
	const DEX_SLOWBRO       ; 87
	const DEX_SLOWKING      ; 88
	const DEX_MAGNEMITE     ; 89
	const DEX_MAGNETON      ; 90
	const DEX_FARFETCHD     ; 91
	const DEX_DODUO         ; 92
	const DEX_DODRIO        ; 93
	const DEX_SEEL          ; 94
	const DEX_DEWGONG       ; 95
	const DEX_GRIMER        ; 96
	const DEX_MUK           ; 97
	const DEX_SHELLDER      ; 98
	const DEX_CLOYSTER      ; 99
	const DEX_GASTLY        ; 100
	const DEX_HAUNTER       ; 101
	const DEX_GENGAR        ; 102
	const DEX_MISDREAVUS    ; 103
	const DEX_ONIX          ; 104
	const DEX_STEELIX       ; 105
	const DEX_DROWZEE       ; 106
	const DEX_HYPNO         ; 107
	const DEX_KRABBY        ; 108
	const DEX_KINGLER       ; 109
	const DEX_VOLTORB       ; 110
	const DEX_ELECTRODE     ; 111
	const DEX_EXEGGCUTE     ; 112
	const DEX_EXEGGUTOR     ; 113
	const DEX_CUBONE        ; 114
	const DEX_MAROWAK       ; 115
	const DEX_MAROWRATH     ; 116
	const DEX_HITMONLEE     ; 117
	const DEX_HITMONCHAN    ; 118
	const DEX_LICKITUNG     ; 119
	const DEX_LICKILICKY    ; 120
	const DEX_KOFFING       ; 121
	const DEX_WEEZING       ; 122
	const DEX_RHYHORN       ; 123
	const DEX_RHYDON        ; 124
	const DEX_CHANSEY       ; 125
	const DEX_TANGELA       ; 126
	const DEX_TANGROWTH     ; 127
	const DEX_KANGASKHAN    ; 128
	const DEX_HORSEA        ; 129
	const DEX_SEADRA        ; 130
	const DEX_KINGDRA       ; 131
	const DEX_GOLDEEN       ; 132
	const DEX_SEAKING       ; 133
	const DEX_STARYU        ; 134
	const DEX_STARMIE       ; 135
	const DEX_MR_MIME       ; 138
	const DEX_SCYTHER       ; 139
	const DEX_SCIZOR        ; 140
	const DEX_JYNX          ; 141
	const DEX_ELECTABUZZ    ; 142
	const DEX_MAGMAR        ; 143
	const DEX_PINSIR        ; 144
	const DEX_PLUX          ; 145
	const DEX_HERACROSS     ; 146
	const DEX_TAUROS        ; 147
	const DEX_MAGIKARP      ; 148
	const DEX_GYARADOS      ; 149
	const DEX_LAPRAS        ; 150
	const DEX_MARILL        ; 136
	const DEX_AZUMARILL     ; 137
	const DEX_SNEASEL       ; 152
	const DEX_DITTO         ; 155
	const DEX_EEVEE         ; 156
	const DEX_VAPOREON      ; 157
	const DEX_JOLTEON       ; 158
	const DEX_FLAREON       ; 159
	const DEX_UMBREON       ; 160
	const DEX_ESPEON        ; 161
	const DEX_PORYGON       ; 162
	const DEX_OMANYTE       ; 163
	const DEX_OMASTAR       ; 164
	const DEX_KABUTO        ; 165
	const DEX_KABUTOPS      ; 166
	const DEX_AERODACTYL    ; 167
	const DEX_ANCHORAGE     ; 151
	const DEX_WOLFMAN       ; 153
	const DEX_WARWOLF       ; 154
	const DEX_SNORLAX       ; 168
	const DEX_ARTICUNO      ; 169
	const DEX_ZAPDOS        ; 170
	const DEX_MOLTRES       ; 171
	const DEX_DRATINI       ; 172
	const DEX_DRAGONAIR     ; 173
	const DEX_DRAGONITE     ; 174
	const DEX_LARVITAR      ; 175
	const DEX_PUPITAR       ; 176
	const DEX_TYRANITAR     ; 177
	const DEX_LUGIA         ; 178
	const DEX_HOOH          ; 179
	const DEX_MEWTWO        ; 180
	const DEX_MEWTWO_ARMOR  ; 181
	const DEX_MEW           ; 182
	const DEX_MISSINGNO     ; 183

NUM_POKEMON    EQU 183

; Special unobtainable mons
	const DEX_CHARIZARD_S
	const DEX_VENUSAUR_S
	const DEX_ELECTABUZZ_S
	const DEX_NINETALES_S
	const DEX_BLASTOISE_S
	const DEX_SCIZOR_S
	const DEX_MAGMAR_S
