	tilepal 0, GRAY, BROWN, BROWN, TEXT, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, BROWN, BROWN, GRAY, BROWN, GRAY
	tilepal 0, GRAY, BROWN, ROOF, BROWN, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, ROOF, ROOF, BROWN, ROOF, ROOF, GRAY, GRAY, GREEN, GREEN, GREEN, GRAY
	tilepal 0, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF, GREEN, GRAY, GRAY, BROWN, GREEN, GREEN, GRAY
	tilepal 0, GREEN, GREEN, RED, RED, WATER, WATER, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, ROOF, ROOF, GRAY, GRAY
	tilepal 0, GREEN, GREEN, GREEN, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, ROOF, ROOF, GRAY, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
