	tilepal 0, GRAY, ROOF, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, ROOF, ROOF, GRAY, GRAY, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, ROOF, ROOF, GRAY, GRAY, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GREEN, YELLOW, GREEN, GRAY, GRAY, BROWN, ROOF, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, BROWN, BROWN, ROOF, BROWN, BROWN, ROOF, ROOF, ROOF, GRAY, GRAY, ROOF
	tilepal 0, GRAY, GRAY, GREEN, GRAY, BROWN, BROWN, BROWN, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, WATER, BROWN
	tilepal 0, GRAY, GRAY, GREEN, BROWN, BROWN, ROOF, GRAY, GREEN, GRAY, GREEN, GRAY, GRAY, RED, RED, RED, RED
