	tilepal 0, RED, BROWN, BROWN, BROWN, WATER, ROOF, BROWN, ROOF, ROOF, WATER, GREEN, WATER, WATER, GRAY, WATER, WATER
	tilepal 0, ROOF, BROWN, BROWN, BROWN, WATER, GRAY, GRAY, ROOF, ROOF, GRAY, GREEN, WATER, WATER, GRAY, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, ROOF, WATER, WATER, WATER, RED, RED, WATER, WATER, RED, RED, RED, RED
	tilepal 0, TEXT, TEXT, TEXT, TEXT, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN
	tilepal 0, ROOF, ROOF, GREEN, GREEN, GREEN, GREEN, GREEN, ROOF, ROOF, ROOF, ROOF, ROOF, RED, RED, RED, RED
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED
