	tilepal 0, GRAY, GRAY, BROWN, GRAY, GRAY, GREEN, GREEN, BROWN, WATER, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, GRAY, WATER, GREEN, GREEN, BROWN, WATER, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, TEXT, YELLOW, WATER, WATER, BROWN, ROOF, BROWN, BROWN, WATER, WATER, WATER, WATER, WATER, ROOF
	tilepal 0, ROOF, ROOF, TEXT, GRAY, GRAY, BROWN, BROWN, ROOF, BROWN, BROWN, WATER, WATER, WATER, GRAY, GRAY, ROOF
	tilepal 0, GRAY, GRAY, TEXT, GRAY, BROWN, BROWN, YELLOW, WATER, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, GRAY, GRAY, TEXT, BROWN, BROWN, GRAY, GRAY, WATER, GRAY, WATER, GRAY, GRAY, WATER, WATER, GRAY, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
