	tilepal 0, BROWN, GREEN, GRAY, GRAY, WATER, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, GREEN, GREEN, GREEN, GREEN, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, BROWN, BROWN, WATER, WATER, BROWN, BROWN, BROWN, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, BROWN, BROWN, GRAY, BROWN, BROWN, WATER, WATER, GRAY, WATER, BROWN, WATER, WATER, WATER, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, TEXT, GRAY, TEXT, GRAY, GRAY, GRAY, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
