	tilepal 0, GRAY, BROWN, BROWN, TEXT, BROWN, WATER, RED, BROWN, BROWN, WATER, WATER, BROWN, BROWN, WATER, WATER, GRAY
	tilepal 0, WATER, BROWN, BROWN, BROWN, WATER, BROWN, RED, BROWN, BROWN, WATER, WATER, BROWN, BROWN, WATER, WATER, BROWN
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, WATER, WATER, GRAY, GRAY, WATER, GRAY, GRAY, GRAY, BROWN, GRAY, WATER, GRAY, ROOF, ROOF, WATER, BROWN
	tilepal 0, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, GRAY, GRAY
	tilepal 0, GREEN, GREEN, WATER, WATER, WATER, GRAY, WATER, WATER, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
