	tilepal 0, WATER, GRAY, GRAY, GRAY, ROOF, GRAY, WATER, WATER, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY, WATER, WATER, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, WATER, WATER, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, WATER
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN, WATER, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
