	tilepal 0, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, WATER, BROWN, BROWN, ROOF, ROOF, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, WATER, BROWN, BROWN, ROOF, ROOF, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY, BROWN, BROWN, GRAY
	tilepal 0, WATER, ROOF, ROOF, ROOF, GRAY, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, ROOF, ROOF, ROOF, ROOF, WATER, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, BROWN, BROWN, TEXT, TEXT, TEXT, TEXT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
