	tilepal 0, GRAY, GREEN, GRAY, GRAY, RED, WATER, GREEN, ROOF, ROOF, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, WATER, GRAY, GRAY, RED, WATER, GREEN, ROOF, ROOF, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, GREEN, WATER, WATER, WATER, WATER, WATER, WATER, YELLOW, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, YELLOW, WATER, GRAY, GRAY, GRAY, GRAY, WATER, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, GRAY, WATER, WATER, GREEN, GREEN, GRAY, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GREEN, GREEN, GRAY, ROOF, WATER, WATER, GRAY, RED
