	tilepal 0, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN, TEXT, TEXT, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT
	tilepal 0, GRAY, GREEN, BROWN, BROWN, GREEN, YELLOW, TEXT, TEXT, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 0, WATER, TEXT, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, YELLOW, BROWN, TEXT, TEXT, GRAY, BROWN, BROWN, BROWN
	tilepal 0, TEXT, TEXT, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, YELLOW, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, BROWN, BROWN, TEXT, TEXT, TEXT, TEXT, GRAY, GRAY, TEXT, GRAY
	tilepal 0, BROWN, TEXT, TEXT, TEXT, TEXT, BROWN, BROWN, YELLOW, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, GRAY, RED
	tilepal 0, GRAY, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT, GRAY, GRAY, GRAY, GRAY, TEXT, GRAY, GRAY, TEXT, TEXT
	tilepal 0, GRAY, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
