	tilepal 0, GRAY, BROWN, BROWN, WATER, WATER, GRAY, GRAY, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, WATER
	tilepal 0, WATER, BROWN, WATER, RED, WATER, GRAY, GRAY, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, BROWN, GRAY, BROWN, WATER, WATER, BROWN, WATER, WATER, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, WATER, WATER, YELLOW, YELLOW, GREEN, GREEN, TEXT, TEXT, YELLOW, YELLOW, RED, RED, GREEN, GREEN
	tilepal 0, GRAY, GRAY, WATER, WATER, YELLOW, YELLOW, GREEN, GREEN, TEXT, TEXT, YELLOW, YELLOW, RED, RED, GREEN, GREEN
	tilepal 0, BROWN, BROWN, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
