	tilepal 0, GRAY, GREEN, TEXT, TEXT, WATER, WATER, GRAY, GRAY, WATER, GRAY, WATER, GREEN, RED, GRAY, WATER, WATER
	tilepal 0, WATER, GREEN, TEXT, TEXT, WATER, WATER, GRAY, BROWN, WATER, WATER, GRAY, GREEN, RED, BROWN, WATER, WATER
	tilepal 0, GREEN, GREEN, BROWN, BROWN, RED, RED, RED, RED, GRAY, WATER, RED, RED, WATER, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, BROWN, BROWN, RED, RED, GRAY, RED, WATER, GRAY, GRAY, GRAY, GRAY, RED, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, RED, RED, WATER, WATER, WATER, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, RED, RED, WATER, WATER, WATER, RED, RED, RED, RED, RED, TEXT, TEXT, TEXT, TEXT
