	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, YELLOW, YELLOW, GRAY, GRAY, GREEN
	tilepal 0, GRAY, GRAY, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, YELLOW, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
