	tilepal 0, GRAY, GRAY, WATER, WATER, BROWN, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER, RED, RED
	tilepal 0, GRAY, RED, WATER, WATER, WATER, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER, RED, RED
	tilepal 0, GRAY, GRAY, RED, BROWN, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, WATER, WATER, RED, GRAY, RED, GRAY, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER, WATER, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
