	tilepal 0, WATER, RED, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, BROWN, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, BROWN, GRAY, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER
	tilepal 0, RED, WATER, WATER, WATER, WATER, WATER, RED, RED, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER, WATER
