	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, RED
	tilepal 0, RED, RED, RED, RED, RED, BROWN, BROWN, RED, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, RED
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, BROWN, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, BROWN, BROWN, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED
