VileplumePicFront::    INCBIN "gfx/pokemon/front/vileplume.pic"
VileplumePicBack::     INCBIN "gfx/pokemon/back/vileplumeb.pic"
BellsproutPicFront::   INCBIN "gfx/pokemon/front/bellsprout.pic"
BellsproutPicBack::    INCBIN "gfx/pokemon/back/bellsproutb.pic"
WeepinbellPicFront::   INCBIN "gfx/pokemon/front/weepinbell.pic"
WeepinbellPicBack::    INCBIN "gfx/pokemon/back/weepinbellb.pic"
VictreebelPicFront::   INCBIN "gfx/pokemon/front/victreebel.pic"
VictreebelPicBack::    INCBIN "gfx/pokemon/back/victreebelb.pic"
MewPicFront::	       INCBIN "gfx/pokemon/front/mew.pic"
MewPicBack::	       INCBIN "gfx/pokemon/back/mewb.pic"

SteelixPicFront::	   INCBIN "gfx/pokemon/front/steelix.pic"
SteelixPicBack::	   INCBIN "gfx/pokemon/back/steelixb.pic"
ScizorPicFront::	   INCBIN "gfx/pokemon/front/scizor.pic"
ScizorPicBack::	       INCBIN "gfx/pokemon/back/scizorb.pic"
UmbreonPicFront::      INCBIN "gfx/pokemon/front/umbreon.pic"
UmbreonPicBack::	   INCBIN "gfx/pokemon/back/umbreonb.pic"

FossilKabutopsPic::    INCBIN "gfx/other/fossilkabutops.pic"
FossilAerodactylPic::  INCBIN "gfx/other/fossilaerodactyl.pic"
GhostPic::             INCBIN "gfx/other/ghost.pic"
MissingnoPic::         INCBIN "gfx/other/missingno.pic"