ItemNames:
	db "MasterBall@"
	db "Hyper Ball@"
	db "Super Ball@"
	db "Poké Ball@"
	db "Carte@"
	db "Bicyclette@"
	db "Planche Surf@"	;joenote - give the surfboard it's fan name instead of ?????
	db "Safari Ball@"
	db "Pokédex@"
	db "Pierre Lune@"
	db "Antidote@"
	db "Anti-Brûle@"
	db "AntiGel@"
	db "Réveil@"
	db "Anti-Para@"
	db "Guérison@"
	db "Potion Max@"
	db "Hyper Potion@"
	db "Super Potion@"
	db "Potion@"
	db "Badge Roche@"
	db "BadgeCascade@"
	db "Badge Foudre@"
	db "Badge Prisme@"
	db "Badge Ame@"
	db "Badge Marais@"
	db "Badge Volcan@"
	db "Badge Terre@"
	db "Corde Sortie@"
	db "Repousse@"
	db "Vieil Ambre@"
	db "Pierre Feu@"
	db "PierreFoudre@"
	db "Pierre Eau@"
	db "PV Plus@"
	db "Protéine@"
	db "Fer@"
	db "Carbone@"
	db "Calcium@"
	db "Super Bonbon@"
	db "Fossile Dôme@"
	db "Nautile@"
	db "Clé Secrète@"
	db "?????@"
	db "Bon Commande@"
	db "Précision +@"
	db "PierrePlante@"
	db "Carte Magn.@"
	db "Pépite@"
	db "Modif.Gène@"
	db "PokéPoupée@"
	db "Total Soin@"
	db "Rappel@"
	db "Rappel Max@"
	db "Défense Spéc@"
	db "Superepousse@"
	db "Max Repousse@"
	db "Muscle +@"
	db "Jetons@"
	db "Eau Fraiche@"
	db "Soda Cool@"
	db "Limonade@"
	db "Passe Bateau@"
	db "Dent d'Or@"
	db "Attaque +@"
	db "Défense +@"
	db "Vitesse +@"
	db "Spécial +@"
	db "Boite Jeton@"
	db "Colis Chen@"
	db "Cherch'Objet@"
	db "Scope Sylphe@"
	db "PokéFlute@"
	db "Clé Asc.@"
	db "Multi Exp@"
	db "Canne@"
	db "Super Canne@"
	db "Méga Canne@"
	db "PP Plus@"
	db "Huile@"
	db "Huile Max@"
	db "Elixir@"
	db "Max Elixir@"
	db "2ème ss@"
	db "1er ss@"
	db "Rdc@"
	db "1er étage@"
	db "2ème étage@"
	db "3ème étage@"
	db "4ème étage@"
	db "5ème étage@"
	db "6ème étage@"
	db "7ème étage@"
	db "8ème étage@"
	db "9ème étage@"
	db "10ème étage@"
	db "4ème ss@"
	db "Peau Métal@" ;dafthunk #19
