ItemNames:
	db "Master ball@"
	db "Hyper ball@"
	db "Super ball@"
	db "Poké ball@"
	db "Carte@"
	db "Bicyclette@"
	db "Planche de surf@"	;joenote - give the surfboard it's fan name instead of ?????
	db "Safari ball@"
	db "Pokédex@"
	db "Pierre Lune@"
	db "Antidote@"
	db "Anti-brûle@"
	db "Antigel@"
	db "Réveil@"
	db "Anti-para@"
	db "Guérison@"
	db "Potion max@"
	db "Hyper potion@"
	db "Super potion@"
	db "Potion@"
	db "Badge roche@"
	db "Badgecascade@"
	db "Badge foudre@"
	db "Badge prisme@"
	db "Badge âme@"
	db "Badge marais@"
	db "Badge volcan@"
	db "Badge terre@"
	db "Corde sortie@"
	db "Repousse@"
	db "Vieil ambre@"
	db "Pierre feu@"
	db "Pierrefoudre@"
	db "Pierre eau@"
	db "PV plus@"
	db "Protéine@"
	db "Fer@"
	db "Carbone@"
	db "Calcium@"
	db "Super bonbon@"
	db "Fossile dôme@"
	db "Nautile@"
	db "Clé secrète@"
	db "?????@"
	db "Bon commande@"
	db "Précision +@"
	db "Pierreplante@"
	db "Carte magn.@"
	db "Pépite@"
	db "PP plus@"
	db "Poképoupée@"
	db "Total soin@"
	db "Rappel@"
	db "Rappel max@"
	db "Défense spéc@"
	db "Superepousse@"
	db "Max repousse@"
	db "Muscle +@"
	db "Jetons@"
	db "Eau fraiche@"
	db "Soda cool@"
	db "Limonade@"
	db "Passe bateau@"
	db "Dent d'or@"
	db "Attaque +@"
	db "Défense +@"
	db "Vitesse +@"
	db "Spécial +@"
	db "Boite jeton@"
	db "Colis Chen@"
	db "Cherch'objet@"
	db "Scope sylphe@"
	db "Pokéflute@"
	db "Clé asc.@"
	db "Multi exp@"
	db "Canne@"
	db "Super canne@"
	db "Méga canne@"
	db "PP plus@"
	db "Huile@"
	db "Huile max@"
	db "Elixir@"
	db "Max élixir@"
	db "2ème ss@"
	db "1er ss@"
	db "Rdc@"
	db "1er étage@"
	db "2ème étage@"
	db "3ème étage@"
	db "4ème étage@"
	db "5ème étage@"
	db "6ème étage@"
	db "7ème étage@"
	db "8ème étage@"
	db "9ème étage@"
	db "10ème étage@"
	db "4ème ss@"
