ItemNames:
	db "Masterball@"
	db "Hyper ball@"
	db "Super ball@"
	db "Poké ball@"
	db "Carte@"
	db "Bicyclette@"
	db "Planche de surf@"	;joenote - give the surfboard it's fan name instead of ?????
	db "Safari ball@"
	db "Pokédex@"
	db "Pierre Lune@"
	db "Antidote@"
	db "Anti-brûle@"
	db "Antigel@"
	db "Réveil@"
	db "Anti-para@"
	db "Guérison@"
	db "Potion max@"
	db "Hyper potion@"
	db "Super potion@"
	db "Potion@"
	db "Badge Roche@"
	db "BadgeCascade@"
	db "Badge Foudre@"
	db "Badge Prisme@"
	db "Badge Ame@"
	db "Badge Marais@"
	db "Badge Volcan@"
	db "Badge Terre@"
	db "Corde sortie@"
	db "Repousse@"
	db "Vieil Ambre@"
	db "Pierre Feu@"
	db "PierreFoudre@"
	db "Pierre Eau@"
	db "PV plus@"
	db "Protéine@"
	db "Fer@"
	db "Carbone@"
	db "Calcium@"
	db "Super bonbon@"
	db "Fossile Dôme@"
	db "Nautile@"
	db "Clé Secrète@"
	db "?????@"
	db "Bon Commande@"
	db "Précision +@"
	db "PierrePlante@"
	db "Carte Magn.@"
	db "Pépite@"
	db "PP plus@"
	db "PokéPoupée@"
	db "Total soin@"
	db "Rappel@"
	db "Rappel max@"
	db "Défense spéc@"
	db "Superepousse@"
	db "Max repousse@"
	db "Muscle +@"
	db "Jetons@"
	db "Eau fraiche@"
	db "Soda cool@"
	db "Limonade@"
	db "Passe Bateau@"
	db "Dent d'or@"
	db "Attaque +@"
	db "Défense +@"
	db "Vitesse +@"
	db "Spécial +@"
	db "Boite Jeton@"
	db "Colis Chen@"
	db "Cherch'Objet@"
	db "Scope Sylphe@"
	db "PokéFlute@"
	db "Clé Asc.@"
	db "Multi Exp@"
	db "Canne@"
	db "Super Canne@"
	db "Méga Canne@"
	db "PP plus@"
	db "Huile@"
	db "Huile max@"
	db "Elixir@"
	db "Max élixir@"
	db "2ème ss@"
	db "1er ss@"
	db "Rdc@"
	db "1er étage@"
	db "2ème étage@"
	db "3ème étage@"
	db "4ème étage@"
	db "5ème étage@"
	db "6ème étage@"
	db "7ème étage@"
	db "8ème étage@"
	db "9ème étage@"
	db "10ème étage@"
	db "4ème ss@"
	db "Peau Métal@" ;dafthunk #19
