MoveNames::
	db "Ecras'Face@"
	db "Poing-Karaté@"
	db "Torgnoles@"
	db "Poing Comète@"
	db "Ultimapoing@"
	db "Jackpot@"
	db "Poing de Feu@"
	db "Poinglace@"
	db "Poing-Eclair@"
	db "Griffe@"
	db "Force Poigne@"
	db "Guillotine@"
	db "Coupe-vent@"
	db "Danse-Lames@"
	db "Coupe@"
	db "Tornade@"
	db "Cru-Aile@"
	db "Cyclone@"
	db "Vol@"
	db "Etreinte@"
	db "Souplesse@"
	db "Fouet Lianes@"
	db "Ecrasement@"
	db "Double Pied@"
	db "Ultimawashi@"
	db "Pied Sauté@"
	db "Mawashi Geri@"
	db "Jet de Sable@"
	db "Coup d'Boule@"
	db "Koud'Korne@"
	db "Furie@"
	db "Empal'Korne@"
	db "Charge@"
	db "Plaquage@"
	db "Ligotage@"
	db "Belier@"
	db "Mania@"
	db "Damoclès@"
	db "Mimi-Queue@"
	db "Dard-Venin@"
	db "Double-Dard@"
	db "Dard-Nuée@"
	db "Groz'Yeux@"
	db "Morsure@"
	db "Rugissement@"
	db "Hurlement@"
	db "Berceuse@"
	db "Ultrason@"
	db "Sonicboom@"
	db "Entrave@"
	db "Acide@"
	db "Flammèche@"
	db "Lance-Flamme@"
	db "Brume@"
	db "Pistolet a O@"
	db "Hydrocanon@"
	db "Surf@"
	db "Laser Glace@"
	db "Blizzard@"
	db "Rafale Psy@"
	db "Bulles d'O@"
	db "Onde Boréale@"
	db "Ultralaser@"
	db "Picpic@"
	db "Bec Vrille@"
	db "Sacrifice@"
	db "Balayage@"
	db "Riposte@"
	db "Frappe Atlas@"
	db "Force@"
	db "Vol-Vie@"
	db "Méga-Sangsue@"
	db "Vampigraine@"
	db "Croissance@"
	db "Tranch'Herbe@"
	db "Lance-Soleil@"
	db "Poudre Toxik@"
	db "Para-Spore@"
	db "Poudre Dodo@"
	db "Danse-Fleur@"
	db "Sécrétion@"
	db "Draco-Rage@"
	db "Danseflamme@"
	db "Eclair@"
	db "Tonnerre@"
	db "Cage-Eclair@"
	db "Fatal-Foudre@"
	db "Jet-Pierres@"
	db "Séisme@"
	db "Abime@"
	db "Tunnel@"
	db "Toxik@"
	db "Choc Mental@"
	db "Psyko@"
	db "Hypnose@"
	db "Yoga@"
	db "Hâte@"
	db "Vive-Attaque@"
	db "Frénésie@"
	db "Téléport@"
	db "Ténèbres@"
	db "Copie@"
	db "Grincement@"
	db "Reflet@"
	db "Soin@"
	db "Armure@"
	db "Lilliput@"
	db "Brouillard@"
	db "Onde Folie@"
	db "Repli@"
	db "Boul'Armure@"
	db "Bouclier@"
	db "Mur Lumière@"
	db "Buée Noire@"
	db "Protection@"
	db "Puissance@"
	db "Patience@"
	db "Métronome@"
	db "Mimique@"
	db "Destruction@"
	db "Bomb'Oeuf@"
	db "Léchouille@"
	db "Purédpois@"
	db "Détritus@"
	db "Massd'Os@"
	db "Déflagration@"
	db "Cascade@"
	db "Claquoir@"
	db "Météores@"
	db "Coud'Krâne@"
	db "Picanon@"
	db "Constriction@"
	db "Amnésie@"
	db "Télékinésie@"
	db "E-Coque@"
	db "Pied Voltige@"
	db "Intimidation@"
	db "Dévorêve@"
	db "Gaz Toxik@"
	db "Pilonnage@"
	db "Vampirisme@"
	db "Grobisou@"
	db "Piqué@"
	db "Morphing@"
	db "Ecume@"
	db "Uppercut@"
	db "Spore@"
	db "Flash@"
	db "Vague Psy@"
	db "Trempette@"
	db "Acidarmure@"
	db "Pince-Masse@"
	db "Explosion@"
	db "Combo-Griffe@"
	db "Osmerang@"
	db "Repos@"
	db "Eboulement@"
	db "Croc de Mort@"
	db "Affûtage@"
	db "Adaptation@"
	db "Triplattaque@"
	db "Croc Fatal@"
	db "Tranche@"
	db "Clonage@"
	db "Bomb-Beurk@"   ; dafthunk #46
	db "Poursuite@"    ; dafthunk #20
	db "Mâchouille@"   ; dafthunk #20
	db "Griffe Acier@" ; dafthunk #20
	db "Queue de Fer@" ; dafthunk #20
	db "Lutte@"
