MoveNames::
	db "Ecras'face@"
	db "Poing-karate@"
	db "Torgnoles@"
	db "Poing comete@"
	db "Ultimapoing@"
	db "Jackpot@"
	db "Poing de feu@"
	db "Poinglace@"
	db "Poing-eclair@"
	db "Griffe@"
	db "Force poigne@"
	db "Guillotine@"
	db "Coupe-vent@"
	db "Danse-lames@"
	db "Coupe@"
	db "Tornade@"
	db "Cru-aile@"
	db "Cyclone@"
	db "Vol@"
	db "Etreinte@"
	db "Souplesse@"
	db "Fouet lianes@"
	db "Ecrasement@"
	db "Double pied@"
	db "Ultimawashi@"
	db "Pied saute@"
	db "Mawashi geri@"
	db "Jet de sable@"
	db "Coup d'boule@"
	db "Koud'korne@"
	db "Furie@"
	db "Empal'korne@"
	db "Charge@"
	db "Plaquage@"
	db "Ligotage@"
	db "Belier@"
	db "Mania@"
	db "Damocles@"
	db "Mimi-queue@"
	db "Dard-venin@"
	db "Double-dard@"
	db "Dard-nuee@"
	db "Groz'yeux@"
	db "Morsure@"
	db "Rugissement@"
	db "Hurlement@"
	db "Berceuse@"
	db "Ultrason@"
	db "Sonicboom@"
	db "Entrave@"
	db "Acide@"
	db "Flammeche@"
	db "Lance-flamme@"
	db "Brume@"
	db "Pistolet a o@"
	db "Hydrocanon@"
	db "Surf@"
	db "Laser glace@"
	db "Blizzard@"
	db "Rafale psy@"
	db "Bulles d'o@"
	db "Onde boreale@"
	db "Ultralaser@"
	db "Picpic@"
	db "Bec vrille@"
	db "Sacrifice@"
	db "Balayage@"
	db "Riposte@"
	db "Frappe atlas@"
	db "Force@"
	db "Vol-vie@"
	db "Mega-sangsue@"
	db "Vampigraine@"
	db "Croissance@"
	db "Tranch'herbe@"
	db "Lance-soleil@"
	db "Poudre toxik@"
	db "Para-spore@"
	db "Poudre dodo@"
	db "Danse-fleur@"
	db "Secretion@"
	db "Draco-rage@"
	db "Danseflamme@"
	db "Eclair@"
	db "Tonnerre@"
	db "Cage-eclair@"
	db "Fatal-foudre@"
	db "Jet-pierres@"
	db "Seisme@"
	db "Abime@"
	db "Tunnel@"
	db "Toxik@"
	db "Choc mental@"
	db "Psyko@"
	db "Hypnose@"
	db "Yoga@"
	db "Hate@"
	db "Vive-attaque@"
	db "Frenesie@"
	db "Teleport@"
	db "Tenebres@"
	db "Copie@"
	db "Grincement@"
	db "Reflet@"
	db "Soin@"
	db "Armure@"
	db "Lilliput@"
	db "Brouillard@"
	db "Onde folie@"
	db "Repli@"
	db "Boul'armure@"
	db "Bouclier@"
	db "Mur lumiere@"
	db "Buee noire@"
	db "Protection@"
	db "Puissance@"
	db "Patience@"
	db "Metronome@"
	db "Mimique@"
	db "Destruction@"
	db "Bomb'oeuf@"
	db "Lechouille@"
	db "Puredpois@"
	db "Detritus@"
	db "Massd'os@"
	db "Deflagration@"
	db "Cascade@"
	db "Claquoir@"
	db "Meteores@"
	db "Coud'krane@"
	db "Picanon@"
	db "Constriction@"
	db "Amnesie@"
	db "Telekinesie@"
	db "E-coque@"
	db "Pied voltige@"
	db "Intimidation@"
	db "Devoreve@"
	db "Gaz toxik@"
	db "Pilonnage@"
	db "Vampirisme@"
	db "Grobisou@"
	db "Pique@"
	db "Morphing@"
	db "Ecume@"
	db "Uppercut@"
	db "Spore@"
	db "Flash@"
	db "Vague psy@"
	db "Trempette@"
	db "Acidarmure@"
	db "Pince-masse@"
	db "Explosion@"
	db "Combo-griffe@"
	db "Osmerang@"
	db "Repos@"
	db "Eboulement@"
	db "Croc de mort@"
	db "Affutage@"
	db "Adaptation@"
	db "Triplattaque@"
	db "Croc fatal@"
	db "Tranche@"
	db "Clonage@"
	db "Bomb-beurk@"   ; dafthunk #46
	db "Poursuite@"    ; dafthunk #20
	db "Mâchouille@"   ; dafthunk #20
	db "Griffe acier@" ; dafthunk #20
	db "Queue de fer@" ; dafthunk #20
	db "Lutte@"
