TrainerNames:
	db "Gamin@"
	db "Scout@"
	db "Fillette@"
	db "Marin@"
	db "Dresseur jr♂@"
	db "Dresseur jr♀@"
	db "PokéManiac@"
	db "Intéllo@"
	db "Montagnard@"
	db "Motard@"
	db "Pillard@"
	db "Mécano@"
	db "Jongleur@"
	db "Pêcheur@"
	db "Nageur@"
	db "Loubard@"
	db "Croupier@"
	db "Canon@"
	db "Kinésiste@"
	db "Rocker@"
	db "Jongleur@"
	db "Dompteur@"
	db "Ornithologue@"
	db "Karatéka@"
	db "Rival1@"
	db "Prof.Chen@"
	db "Chef@"
	db "Scientifique@"
	db "Giovanni@"
	db "Rocket@"
	db "TopDresseur♂@"
	db "TopDresseur♀@"
	db "Aldo@"
	db "Pierre@"
	db "Ondine@"
	db "Major Bob@"
	db "Erika@"
	db "Koga@"
	db "Auguste@"
	db "Morgane@"
	db "Gentleman@"
	db "Rival2@"
	db "Rival3@"
	db "Olga@"
	db "Exorciste@"
	db "Agatha@"
	db "Peter@"
	db "Janine@"
	db "Agent Jenny@"
	db "Inf. Joelle@"
